# Generated by Django 4.2.1 on 2023-11-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_images',
            name='related_post',
        ),
    ]
