# Generated by Django 4.2.1 on 2023-11-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='default_images/unknown_pp.jpg', upload_to='profile_pictures'),
        ),
    ]
