# Generated by Django 4.2.1 on 2023-11-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_media', '0002_remove_post_images_related_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_images',
            new_name='Image',
        ),
    ]
