# Generated by Django 4.2.1 on 2023-11-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_media', '0003_rename_post_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_post',
            field=models.ManyToManyField(blank=True, related_name='post_saved_by', to='Notes_media.post'),
        ),
    ]
