# Generated by Django 4.2.1 on 2023-11-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_media', '0004_user_saved_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='Notes_media/pdf_files'),
        ),
    ]
