# Generated by Django 4.2.1 on 2023-11-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_media', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='categoty_posts', to='Notes_media.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='level_posts', to='Notes_media.level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_post',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='Notes_media.post'),
        ),
    ]
