# Generated by Django 4.2.1 on 2023-11-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_media', '0011_post_category_post_level_alter_user_saved_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoty_posts', to='Notes_media.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_posts', to='Notes_media.level'),
        ),
    ]
