# Generated by Django 4.2.1 on 2023-11-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_media', '0012_alter_post_category_alter_post_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(related_name='users_of_this_category', to='Notes_media.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_of_this_level', to='Notes_media.level'),
        ),
    ]
