# Generated by Django 4.2.1 on 2023-11-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_media', '0013_alter_user_category_alter_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='users_of_this_category', to='Notes_media.category'),
        ),
    ]
