# Generated by Django 4.2.1 on 2023-11-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes_media', '0014_alter_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to='profile_pictures'),
        ),
    ]
